name: Build and deploy website

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v16.14.2
      uses: actions/setup-node@v1
      with:
        node-version: '16.14.2'
    
    - run: yarn install
    - run: yarn build
    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
